# generated by zon2nix (https://github.com/Cloudef/zig2nix)

{
  lib,
  linkFarm,
  fetchurl,
  fetchgit,
  runCommandLocal,
  zig,
  name ? "zig-packages",
}:

let
  unpackZigArtifact =
    { name, artifact }:
    runCommandLocal name { nativeBuildInputs = [ zig ]; } ''
      hash="$(zig fetch --global-cache-dir "$TMPDIR" ${artifact})"
      mv "$TMPDIR/p/$hash" "$out"
      chmod 755 "$out"
    '';

  fetchZig =
    {
      name,
      url,
      hash,
    }:
    let
      artifact = fetchurl { inherit url hash; };
    in
    unpackZigArtifact { inherit name artifact; };

  fetchGitZig =
    {
      name,
      url,
      hash,
      rev ? throw "rev is required, remove and regenerate the zon2json-lock file",
    }:
    let
      parts = lib.splitString "#" url;
      url_base = lib.elemAt parts 0;
      url_without_query = lib.elemAt (lib.splitString "?" url_base) 0;
    in
    fetchgit {
      inherit name rev hash;
      url = url_without_query;
      deepClone = false;
    };

  fetchZigArtifact =
    {
      name,
      url,
      hash,
      ...
    }@args:
    let
      parts = lib.splitString "://" url;
      proto = lib.elemAt parts 0;
      path = lib.elemAt parts 1;
      fetcher = {
        "git+http" = fetchGitZig (
          args
          // {
            url = "http://${path}";
          }
        );
        "git+https" = fetchGitZig (
          args
          // {
            url = "https://${path}";
          }
        );
        http = fetchZig {
          inherit name hash;
          url = "http://${path}";
        };
        https = fetchZig {
          inherit name hash;
          url = "https://${path}";
        };
      };
    in
    fetcher.${proto};
in
linkFarm name [
  {
    name = "sdl3-0.1.5-NmT1QxARJgAH1Wp0cMBJDAc9vD7weufTkIwVa5rehA2q";
    path = fetchZigArtifact {
      name = "sdl3";
      url = "git+https://codeberg.org/7Games/zig-sdl3#014b7bcb2899f3ed9c945c4abfcfe1b25d75bfeb";
      hash = "sha256-pEh26+O/2EpRJ6FYS/MbZSaUxL331Hm97lwu4qCtjmc=";
      rev = "014b7bcb2899f3ed9c945c4abfcfe1b25d75bfeb";
    };
  }
  {
    name = "sdl-0.3.1+3.2.24-7uIn9L9AfwFQf90JcTh3Slw__ZA8SEomk6fQI9F8ItY0";
    path = fetchZigArtifact {
      name = "sdl";
      url = "git+https://github.com/castholm/SDL.git?ref=v0.3.1%2B3.2.24#1d4b8dcc03bd216712b55318b4ad2402b5511490";
      hash = "sha256-nbL6IOdzpM3GJmhLwd3yGuxMbfB+LcGhOUeACC0PQC0=";
      rev = "1d4b8dcc03bd216712b55318b4ad2402b5511490";
    };
  }
  {
    name = "sdl_linux_deps-0.0.0-Vy5_h4AlfwBtG7MIPe7ZNUANhmYLek_SA140uYk9SrED";
    path = fetchZigArtifact {
      name = "sdl_linux_deps";
      url = "git+https://github.com/castholm/SDL_linux_deps.git#085212f286621835f2638cb0cfff078fe515341a";
      hash = "sha256-2NWnMwJNl7JzSRq6cym1CJjlEDIlDwvWCfbD+Q1Ig4w=";
      rev = "085212f286621835f2638cb0cfff078fe515341a";
    };
  }
  {
    name = "N-V-__8AAP6WIgI4b7FYvyJ6F7gg38lmxqvHSQPGyTlGuFuT";
    path = fetchZigArtifact {
      name = "sdl_image";
      url = "git+https://github.com/libsdl-org/SDL_image?ref=release-3.2.x#59adab53b95cd553a1c77f1c7665a980e323dfdd";
      hash = "sha256-RwmReDPUZODLueMyrQ8bTIzLoLJi39m+o6yI+HH/zRc=";
      rev = "59adab53b95cd553a1c77f1c7665a980e323dfdd";
    };
  }
  {
    name = "N-V-__8AAK74BwCyuisw6wdXWDDg8sXuHJd_tPk1VKxLTUBK";
    path = fetchZigArtifact {
      name = "sdl_net";
      url = "git+https://github.com/libsdl-org/SDL_net.git#8f5d9df8e42eb31e68aa3aed74ba2ab380e3001e";
      hash = "sha256-MKsUowJLoYeB/whsmpbfFhbEtQFExtEfxSq61B3UT3M=";
      rev = "8f5d9df8e42eb31e68aa3aed74ba2ab380e3001e";
    };
  }
  {
    name = "N-V-__8AAF2JgAA_Y5Qzm3b226N8y7ivM-qFVpCo9NkbfO8Y";
    path = fetchZigArtifact {
      name = "sdl_ttf";
      url = "git+https://github.com/libsdl-org/SDL_ttf#release-3.2.2";
      hash = "sha256-1Gc71BRs6WcPpS2iNXPoCVaPP8dxH/fQ6tyeeqZC09k=";
      rev = "a1ce3670aec736ecbf0936c43f2f0cc53aa61e5b";
    };
  }
  {
    name = "harfbuzz-8.5.0-Ip1VAqCZAADRh-K2AVujG0N3VAal-AKwkZrvlYOaloyB";
    path = fetchZigArtifact {
      name = "harfbuzz";
      url = "git+https://github.com/allyourcodebase/harfbuzz#6bb522d22cee0ce1d1446bd59fa5b0417f25303e";
      hash = "sha256-HDOVWcDc3LYK/wJeM8lCZaeYtjF31ExelThV3b2+Cts=";
      rev = "6bb522d22cee0ce1d1446bd59fa5b0417f25303e";
    };
  }
  {
    name = "N-V-__8AAKwyqQWfrqa-RqyRcNr-9zdBG1SQ6v3eNremxDs3";
    path = fetchZigArtifact {
      name = "harfbuzz";
      url = "https://github.com/harfbuzz/harfbuzz/archive/refs/tags/8.5.0.tar.gz";
      hash = "sha256-etjk4jzndu+2oyL2U5eLPrdjEo/VapAlJ3Xtuf0yeVY=";
    };
  }
  {
    name = "freetype-2.13.3-C3-WdeyJAAD9z8BeYYQ8N3gNlPI9NvHRxg5039S5vhz7";
    path = fetchZigArtifact {
      name = "freetype";
      url = "git+https://github.com/allyourcodebase/freetype#9d847affbd224cf6a7303ad6d98715e3675ef78c";
      hash = "sha256-iqM4ZHoNjLXGmBHP9ZND3S0BipXidmZQOrRsV7WPEjs=";
      rev = "9d847affbd224cf6a7303ad6d98715e3675ef78c";
    };
  }
  {
    name = "N-V-__8AAKfbpwAXnUJ6TJEaqZGWgp6F_8OhiLErejRxQ7Y5";
    path = fetchZigArtifact {
      name = "freetype";
      url = "https://github.com/freetype/freetype/archive/refs/tags/VER-2-13-3.tar.gz";
      hash = "sha256-vFyJjkdW03Pg2ZG6sFMDbF6yqnwNXGfoZi3cbaQMQQM=";
    };
  }
  {
    name = "libpng-1.6.50-oiaFGt4qAAB_vzrtvz9hA7_UiBW4arSaMVGc7ekKMCZ2";
    path = fetchZigArtifact {
      name = "libpng";
      url = "git+https://github.com/allyourcodebase/libpng#d512607515687aa60b975d6a191aef9a692dac87";
      hash = "sha256-uAuTz+uVGGmu/0HOHuuHj+lo6Mn/rT0KahJdZVhB+eg=";
      rev = "d512607515687aa60b975d6a191aef9a692dac87";
    };
  }
  {
    name = "N-V-__8AAGrVXwC00HYe0ep6gbt70MXihr_woI0886_w8tD8";
    path = fetchZigArtifact {
      name = "libpng";
      url = "https://github.com/glennrp/libpng/archive/refs/tags/v1.6.50.tar.gz";
      hash = "sha256-cRWOU8/fKHe8mbyrM2QdeN8/SObg2q0DCv6cuMAxqkY=";
    };
  }
  {
    name = "zlib-1.3.1-ZZQ7lbYMAAAuaZnFj2675ah508w1Oc-EuY1V1cWJka2C";
    path = fetchZigArtifact {
      name = "zlib";
      url = "git+https://github.com/allyourcodebase/zlib#8a8161babd4b79ea47d5a5976337a96ac4a5666b";
      hash = "sha256-is6CcnQ7691a/yZFdTtIW5GpNh/qdA+onx+Er2gizhc=";
      rev = "8a8161babd4b79ea47d5a5976337a96ac4a5666b";
    };
  }
  {
    name = "N-V-__8AAB0eQwD-0MdOEBmz7intriBReIsIDNlukNVoNu6o";
    path = fetchZigArtifact {
      name = "zlib";
      url = "https://github.com/madler/zlib/archive/refs/tags/v1.3.1.tar.gz";
      hash = "sha256-F+iIY/NgBnKrSRgvIXKBtvxNPHYr3jYZNeQ2qVIU0Fw=";
    };
  }
]
